"""Isolated test: does swapping forest Kc from the EVI-Kamble regression (fit on temperate
cropland, using an input variable, EVI, it was never calibrated on) to Negron Juarez et al.
(2008)'s tropical-forest-native ET model close more of B's remaining gap against WWF-SIPA's
baseline?

Real background: the 2026-09-21 factorial decomposition (docs/reports/swy/swy_status_report.qmd,
"Decomposing the gap" section) found QF's gap is essentially all CN (Kc doesn't feed QF at all),
and B's gap is mostly Kc, with CN contributing too. Swapping in her Kc alone (keeping our own CN)
already took B's r from 0.39 to 0.82 and its ratio from 1.48 to 1.21 -- most of the way there, not
all of it. This run tests whether a tropical-forest-appropriate Kc, generated by this project's
own methodology rather than borrowed from her, closes the rest of that gap -- the actual point of
this whole comparison being generalizability, not the Philippines result in isolation (this
project's methodology needs to work anywhere, not just wherever a local expert's hand-calibrated
baseline exists to borrow from).

Everything else here matches `09e_run_swy_ph_snapped_grid.py` exactly (grid-snapped DEM, this
project's own CN via the biophysical table, real WWF-SIPA rain events/precip/ET0) -- own
workspace/results_suffix so this never touches 09e's already-reported output. The ONLY change:
kc_1_path...kc_12_path point at 07d_build_kc_forest_negronjuarez.py's per-pixel rasters (forest
pixels get the Negron Juarez value, everything else falls through to the same table-based Kc
09e already uses) instead of leaving Kc to the flat per-lucode table columns.

Confirmed directly against a local clone of inspring's source this session (not assumed):
`_reclassify_or_clip()` iterates key_field over ['root_depth', 'cn_a', 'cn_b', 'cn_c', 'cn_d',
'kc_1', ..., 'kc_12'] and checks `args[f'{key_field}_path']` before falling back to the CSV table
-- so kc_1_path...kc_12_path are real, valid raster-override args, same mechanism already used
for CN in 09d_run_swy_ph_gcn250_direct.py.

    MSYS_NO_PATHCONV=1 docker run --rm -w /scripts_root -e SWY_DATA_ROOT=/scripts_root/data \\
        --mount type=bind,source="$(pwd)",target=/scripts_root swy_borneo_run:rainfix4 \\
        micromamba run -n geopy311 python \\
        /scripts_root/Python_scripts/swy_philippines_run/09i_run_swy_ph_negronjuarez_forest_kc.py
"""
import os

from osgeo import gdal

DATA_ROOT = os.environ.get("SWY_DATA_ROOT", "/data")


def _reproject_lulc_to_wgs84(src_path, dst_path, dem_path):
    if os.path.exists(dst_path):
        return dst_path
    dem_gt = gdal.Info(dem_path, format="json")["geoTransform"]
    x_res, y_res = abs(dem_gt[1]), abs(dem_gt[5])
    gdal.Warp(
        dst_path,
        src_path,
        dstSRS="EPSG:4326",
        xRes=x_res,
        yRes=y_res,
        resampleAlg="mode",
        srcNodata=128,
        dstNodata=128,
        creationOptions=["COMPRESS=LZW"],
    )
    return dst_path


def _normalize_et0_dir(src_dir, staging_dir):
    import glob
    import re
    import shutil

    os.makedirs(staging_dir, exist_ok=True)
    src_files = glob.glob(os.path.join(src_dir, "*.tif"))
    month_re = re.compile(r"(\d{2})\.tif$")
    found_months = set()
    for src_path in src_files:
        m = month_re.search(os.path.basename(src_path))
        if not m:
            continue
        month = int(m.group(1))
        found_months.add(month)
        dst_path = os.path.join(staging_dir, f"et0_v3_{month:02d}.tif")
        if not os.path.exists(dst_path):
            shutil.copyfile(src_path, dst_path)
    assert found_months == set(range(1, 13)), (
        f"expected months 1-12 in {src_dir}, found {sorted(found_months)}"
    )
    return staging_dir


def main():
    from inspring.seasonal_water_yield import seasonal_water_yield

    inputs_sp = os.path.join(DATA_ROOT, "swy/philippines/INPUTS_SP")
    workspace = os.path.join(DATA_ROOT, "swy/philippines/workspace_becky_inputs_90m_negronjuarez_kc")
    os.makedirs(workspace, exist_ok=True)

    et0_staging = _normalize_et0_dir(
        os.path.join(inputs_sp, "Global-ET0_v3_monthly_tifs"),
        os.path.join(workspace, "et0_v3_normalized"),
    )

    dem_path = os.path.join(DATA_ROOT, "swy/philippines/inputs/dem_srtmgl3_ph_snapped.tif")
    lulc_wgs84_path = _reproject_lulc_to_wgs84(
        os.path.join(inputs_sp, "ph_baseline_lulc_md5_7f29da.tif"),
        os.path.join(workspace, "ph_baseline_lulc_wgs84.tif"),
        dem_path,
    )

    kc_dir = os.path.join(DATA_ROOT, "swy/philippines/inputs/kc_forest_negronjuarez_2020")
    kc_path_args = {
        f"kc_{m}_path": os.path.join(kc_dir, f"kc_{m:02d}.tif") for m in range(1, 13)
    }

    args = {
        "workspace_dir": workspace,
        "results_suffix": "ph_negronjuarez_forest_kc",
        "aoi_path": os.path.join(DATA_ROOT, "swy/philippines/inputs/ph_aoi.gpkg"),
        "dem_raster_path": dem_path,
        "lulc_raster_path": lulc_wgs84_path,
        "lucode_field": "lulc_id",
        "soil_group_path": os.path.join(
            DATA_ROOT, "swy/philippines/inputs/soil_hydrologic_group_hysogs250m_raw_ph.tif"
        ),
        "precip_dir": os.path.join(inputs_sp, "precip_PH_historical_climate_50"),
        "et0_dir": et0_staging,
        # CN and root_depth still come from this table (unaffected -- only Kc is under test here).
        "biophysical_table_path": os.path.join(inputs_sp, "ph_biophysical_table_ncp_kc_cn.csv"),
        # The actual variable under test: forest pixels get Negron Juarez's tropical ET model,
        # everything else falls through to the table's existing Kamble/EVI or fixed Kc -- see
        # 07d_build_kc_forest_negronjuarez.py.
        **kc_path_args,
        "user_defined_rain_events_dir": os.path.join(
            inputs_sp, "n_events_PH_historical_climate_50"
        ),
        "rain_events_table_path": os.path.join(
            DATA_ROOT, "swy/philippines/lulc/rain_events_table.csv"
        ),
        "threshold_flow_accumulation": 1000,
        "alpha_m": 0.018,
        "beta_i": 1,
        "gamma": 1,
        "monthly_alpha": False,
        "user_defined_local_recharge": False,
        "user_defined_climate_zones": False,
        "n_workers": -1,
    }

    print("Calling inspring.seasonal_water_yield.execute() with:")
    for k, v in args.items():
        print(f"  {k}: {v}")

    seasonal_water_yield.execute(args)
    print(f"\nDONE — outputs in {workspace}")


if __name__ == "__main__":
    main()
